syntax on
"set number
set nonumber
set nocompatible
set nosmartcase

set expandtab
set ts=2 st=2 sts=2
set shiftwidth=2

set cursorline

" カーソル行をハイライト
set cursorline
" カレントウィンドウにのみ罫線を引く
augroup cch
  autocmd! cch
  autocmd WinLeave * set nocursorline
  autocmd WinEnter,BufRead * set cursorline
augroup END

:hi clear CursorLine
:hi CursorLine gui=underline
highlight CursorLine ctermbg=black guibg=black

nmap <ESC><ESC> :nohlsearch<CR><ESC>

" 保存時に行末の空白を除去する
"autocmd BufWritePre * :%s/\s\+$//ge
" 保存時にtabをスペースに変換する
"autocmd BufWritePre * :%s/\t/  /ge

" CTRL-hjklでウィンドウ移動
nnoremap <C-j> ;<C-w>j
nnoremap <C-k> ;<C-k>j
nnoremap <C-l> ;<C-l>j
nnoremap <C-h> ;<C-h>j

nnoremap j gj
nnoremap k gk
nnoremap <Down> gj
nnoremap <Up>   gk

set ambiwidth=double

set encoding=utf8
"set fileencodings=utf8,iso-2022-jp,sjis
"set fileencodings=iso-2022-jp,euc-jp,cp932,ucs-bom,utf-8,default,latin1
set fileencodings=iso-2022-jp,utf-8,euc-jp,cp932,ucs-bom,default,latin1
